exclude: null
grid-search:

  "+algorithm": "ac"

  algorithm.total_steps: 50_000
  algorithm.eval_interval: 1_000
  algorithm.video_frames: 100
  algorithm.entropy_coef:
    - 0.001
    - 0.01
    - 0.1

  algorithm.standarize_returns:
    - True
    - False

  algorithm.grad_clip:
    - 0.5
    - 0.1
    - 0.01

  env.name: pettingzoo:pz-mpe-large-spread-v5
  env.time_limit: 50

grid-search-groups:
  alg0:
    - algorithm.name: "CentralV-NoPS"
    - algorithm.model.critic.centralised: True
    - algorithm.model.critic.parameter_sharing: False
    - algorithm.model.actor.parameter_sharing: False
  alg1:
    - algorithm.name: "AC-NoPS"
    - algorithm.model.critic.centralised: False
    - algorithm.model.critic.parameter_sharing: False
    - algorithm.model.actor.parameter_sharing: False
  alg2:
    - algorithm.name: "CentralV-FuPSCritic"
    - algorithm.model.critic.centralised: True
    - algorithm.model.critic.parameter_sharing: True
    - algorithm.model.actor.parameter_sharing: False
  alg3:
    - algorithm.name: "AC-FuPSCritic"
    - algorithm.model.critic.centralised: False
    - algorithm.model.critic.parameter_sharing: True
    - algorithm.model.actor.parameter_sharing: False
  alg4:
    - algorithm.name: "CentralV-FuPSActor"
    - algorithm.model.critic.centralised: True
    - algorithm.model.critic.parameter_sharing: False
    - algorithm.model.actor.parameter_sharing: True
  alg5:
    - algorithm.name: "AC-FuPSActor"
    - algorithm.model.critic.centralised: False
    - algorithm.model.critic.parameter_sharing: False
    - algorithm.model.actor.parameter_sharing: True
  alg6:
    - algorithm.name: "CentralV-FuPS"
    - algorithm.model.critic.centralised: True
    - algorithm.model.critic.parameter_sharing: True
    - algorithm.model.actor.parameter_sharing: True
  alg7:
    - algorithm.name: "AC-FuPS"
    - algorithm.model.critic.centralised: False
    - algorithm.model.critic.parameter_sharing: True
    - algorithm.model.actor.parameter_sharing: True
