# constants
algorithm.log_interval: 10_000
algorithm.save_interval: False
algorithm.eval_interval: 10_000
algorithm.eval_episodes: 10
algorithm.video_interval: False

# top-level choice (grid) search
algorithm.standarize_returns: True
algorithm.lr: 0.0003


algorithm.eps_decay:
  - 2.0
  - 4.0
  - 6.0

algorithm.batch_size:
  - 128
  - 256

hparam-tuples-0:
  - !!python/tuple
    - env.time_limit: 49
    - env.name: lbforaging:Foraging-fixed-20x20-12p-6f-v2
    - algorithm.model.critic.parameter_sharing: "[0,0,0,1,1,1,2,2,2,3,3,3]"
    - algorithm.total_steps: 1_500_000

  - !!python/tuple
    - env.time_limit: 50
    - env.name: pettingzoo:pz-mpe-large-spread-v1
    - algorithm.total_steps: 20_000
    - algorithm.model.critic.parameter_sharing: "[0,0,0,0,0,1,1,1,1,1,2,2,2,2,2]"

  - !!python/tuple
    - env.time_limit: 50
    - env.name: pettingzoo:pz-mpe-large-spread-v2
    - algorithm.total_steps: 20_000
    - algorithm.model.critic.parameter_sharing: "[0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2]"

  - !!python/tuple
    - env.time_limit: 50
    - env.name: pettingzoo:pz-mpe-large-spread-v3
    - algorithm.total_steps: 20_000
    - algorithm.model.critic.parameter_sharing: "[0,0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2,2,3,3,3,3,3,3,4,4,4,4,4,4]"

  - !!python/tuple
    - env.time_limit: 50
    - env.name: pettingzoo:pz-mpe-large-spread-v4
    - algorithm.total_steps: 20_000
    - algorithm.model.critic.parameter_sharing: "[0,0,0,1,1,1,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4]"

  - !!python/tuple
    - env.time_limit: 50
    - env.name: pettingzoo:pz-mpe-large-spread-v5
    - algorithm.total_steps: 20_000
    - algorithm.model.critic.parameter_sharing: "[0,0,0,0,0,1,1,1,1,1,2,2,2,2,2]"

  - !!python/tuple
    - env.time_limit: 50
    - env.name: pettingzoo:pz-mpe-large-spread-v6
    - algorithm.total_steps: 20_000
    - algorithm.model.critic.parameter_sharing: "[0,0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2,2,3,3,3,3,3,3,4,4,4,4,4,4]"

hparam-tuples-1:

  # DQN
  - !!python/tuple 
    - algorithm.name: "DQN-NoPS"
    - "+algorithm": "dqn"
    - algorithm.model.critic.parameter_sharing: False

  - !!python/tuple 
    - algorithm.name: "DQN-FuPS"
    - "+algorithm": "dqn"
    - algorithm.model.critic.parameter_sharing: True

  - !!python/tuple 
    - algorithm.name: "DQN-FuPS+id"
    - "+algorithm": "dqn"
    - env.observe_id: True
    - algorithm.model.critic.parameter_sharing: True

  - !!python/tuple 
    - algorithm.name: "DQN-SePS"
    - "+algorithm": "dqn"

  # VDN
  - !!python/tuple 
    - algorithm.name: "VDN-NoPS"
    - "+algorithm": "vdn"
    - algorithm.model.critic.parameter_sharing: False

  - !!python/tuple 
    - algorithm.name: "VDN-FuPS"
    - "+algorithm": "vdn"
    - algorithm.model.critic.parameter_sharing: True

  - !!python/tuple 
    - algorithm.name: "VDN-FuPS+id"
    - "+algorithm": "vdn"
    - env.observe_id: True
    - algorithm.model.critic.parameter_sharing: True

  - !!python/tuple 
    - algorithm.name: "VDN-SePS"
    - "+algorithm": "vdn"

